#!/usr/bin/env python3
"""
Reporter Agent — technical writer for narrative reports.

Assembles structured reports from prediction/optimization data in the
conversation history, respecting confidence-level constraints on precision.
"""

from typing import List
from langchain_core.tools import tool
from pydantic import BaseModel, Field

from .network_components import BasicAgent, SystemPrompt, ReportOutput



class ReportInput(BaseModel):
    title: str = Field(..., description="Report title")
    executive_summary: str = Field(..., description="2-3 sentence overview")
    geometry_description: str = Field(..., description="Geometry and setup section")
    results_section: str = Field(
        ..., description="Results respecting confidence level constraints"
    )
    reliability_section: str = Field(..., description="Reliability assessment")
    recommendations: str = Field(..., description="Recommendations and next steps")


@tool("Generate_Report", args_schema=ReportInput)
def generate_report(
    title: str,
    executive_summary: str,
    geometry_description: str,
    results_section: str,
    reliability_section: str,
    recommendations: str,
):
    """Assemble the final markdown report from LLM-written sections."""
    md = f"""# {title}

## Executive Summary
{executive_summary}

## Geometry & Setup
{geometry_description}

## Results
{results_section}

## Reliability Assessment
{reliability_section}

## Recommendations
{recommendations}

---
*Generated by PI-GINOT Agentic Studio.*
"""
    return "Report generated.", [ReportOutput(
        title=title,
        markdown=md,
        sections=[
            {"name": "Executive Summary", "content": executive_summary},
            {"name": "Geometry & Setup", "content": geometry_description},
            {"name": "Results", "content": results_section},
            {"name": "Reliability", "content": reliability_section},
            {"name": "Recommendations", "content": recommendations},
        ],
    )]


def _build_system_prompt():
    return SystemPrompt(
        role=(
            "You are the **Reporter** — a technical writer who assembles narrative "
            "reports from prediction data already in the conversation history."
        ),
        task="""## Workflow
1. Scan the conversation for the most recent prediction / optimization / refinement.
2. Write 5 sections (executive summary, geometry, results, reliability, recommendations).
3. Respect confidence-level constraints when writing Results:
   - HIGH → full precision numbers
   - MEDIUM → 2 sig figs with "approximate" qualifiers
   - LOW → 1 sig fig or ranges, trends only
   - REJECT → describe issues, no numbers
4. Call `Generate_Report` with all sections filled in.

## Quality rules
- Cite specific diagnostic values in the Reliability section
- Mention verification grid seed for reproducibility
- Honest limitations — don't overstate
- If refinement was applied, mention the provenance update""",
    )


def get_agent(llm, ltm=None):
    """Create and return the Reporter agent."""
    return BasicAgent(
        agent_name="Reporter",
        system_prompt=_build_system_prompt(),
        llm=llm,
        tools=[generate_report],
        return_all_messages=True,
        ltm=ltm,
    )
